name: flutter
environment:
  sdk: ^3.7.0-0
dependencies:
  characters: 1.3.0
  collection: 1.19.0
  wdq: 0.11.1
  meta: 1.15.0
  vector_math: 2.1.4
  sky_engine:
    sdk: flutter
dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_goldens:  
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fake_async: 1.3.2
  leak_tracker_flutter_testing: 3.0.9
  leak_tracker_testing: 3.0.1
  leak_tracker: 10.0.8
  web: 1.1.0
  async: 2.12.0
  boolean_selector: 2.1.2
  clock: 1.1.2
  crypto: 3.0.6
  file: 7.0.1
  intl: 0.19.0
  matcher: 0.12.16+1
  path: 1.9.1
  platform: 3.1.6
  process: 5.0.3
  source_span: 1.10.1
  stack_trace: 1.12.0
  stream_channel: 2.1.2
  string_scanner: 1.4.0
  sync_http: 0.3.1
  term_glyph: 1.2.1
  test_api: 0.7.4
  typed_data: 1.4.0
  vm_service: 14.3.1
  webdriver: 3.0.4